# Generated by Codex on 2026-02-24

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomAnalyticsSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bloom_level', models.IntegerField()),
                ('average_score', models.FloatField(default=0.0)),
                ('pass_rate', models.FloatField(default=0.0)),
                ('attempts_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloom_snapshots', to='organizations.organization')),
            ],
            options={
                'db_table': 'bloom_analytics_snapshots',
                'indexes': [
                    models.Index(fields=['organization', 'bloom_level'], name='bloom_anal_organiza_6e9878_idx'),
                    models.Index(fields=['created_at'], name='bloom_anal_created_6c6609_idx'),
                ],
            },
        ),
    ]
