# Generated by Django 5.0.2 on 2026-02-24 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_bloom_analytics_snapshot'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('scheduled', 'Scheduled'), ('manual', 'Manual')], default='scheduled', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'analytics_jobs',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_id', models.CharField(max_length=100)),
                ('actor_name', models.CharField(blank=True, max_length=255)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], default='system', max_length=20)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, max_length=100)),
                ('target_type', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.CreateModel(
            name='GenieReportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipients', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genie_report_runs',
            },
        ),
        migrations.CreateModel(
            name='GenieReportSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('recipients', models.TextField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genie_report_schedules',
            },
        ),
        migrations.CreateModel(
            name='ManagerDigestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('roles', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'manager_digest_runs',
            },
        ),
        migrations.RenameIndex(
            model_name='bloomanalyticssnapshot',
            new_name='bloom_analy_organiz_dfacc4_idx',
            old_name='bloom_anal_organiza_6e9878_idx',
        ),
        migrations.RenameIndex(
            model_name='bloomanalyticssnapshot',
            new_name='bloom_analy_created_e09f83_idx',
            old_name='bloom_anal_created_6c6609_idx',
        ),
        migrations.AddField(
            model_name='analyticsjob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='geniereportrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='geniereportschedule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='geniereportrun',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.geniereportschedule'),
        ),
        migrations.AddField(
            model_name='managerdigestrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'action'], name='audit_logs_organiz_9c5b7f_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='audit_logs_timesta_423be6_idx'),
        ),
    ]
