# Generated by Django 5.0.2 on 2026-02-24 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_analyticsjob_auditlog_geniereportrun_and_more'),
        ('competencies', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyTrajectoryForecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forecast', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencies.competency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_trajectory_forecasts', to='organizations.organization')),
            ],
            options={
                'db_table': 'competency_trajectory_forecasts',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='competency__organiz_e30a0f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceReadinessPrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prediction', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_readiness_predictions', to='organizations.organization')),
            ],
            options={
                'db_table': 'compliance_readiness_predictions',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='compliance__organiz_eeb65b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DepartmentBloomTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bloom_level', models.IntegerField()),
                ('trend', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_bloom_trends', to='organizations.organization')),
            ],
            options={
                'db_table': 'department_bloom_trends',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='department__organiz_ac51f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='StrategicSkillShortageDetection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shortage', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_shortage_detections', to='organizations.organization')),
            ],
            options={
                'db_table': 'strategic_skill_shortage_detection',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='strategic_s_organiz_cfbf6d_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkforceCapabilityIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0.0)),
                ('trend', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_capability_indices', to='organizations.organization')),
            ],
            options={
                'db_table': 'workforce_capability_index',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='workforce_c_organiz_ac778f_idx')],
            },
        ),
    ]
