# Generated by Django 5.0.2 on 2026-02-24 23:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('course_assigned', 'Course Assigned'), ('enrollment_new', 'Enrollment New'), ('course_completed', 'Course Completed'), ('achievement_earned', 'Achievement Earned'), ('assessment_due', 'Assessment Due'), ('certificate_issued', 'Certificate Issued'), ('certificate_expiring', 'Certificate Expiring'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('enrollment_created', 'Enrollment Created'), ('enrollment_overdue', 'Enrollment Overdue'), ('enrollment_reminder', 'Enrollment Reminder'), ('policy_updated', 'Policy Updated'), ('manager_digest', 'Manager Digest'), ('feedback_received', 'Feedback Received')], max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('course_assigned', 'Course Assigned'), ('enrollment_new', 'Enrollment New'), ('course_completed', 'Course Completed'), ('achievement_earned', 'Achievement Earned'), ('assessment_due', 'Assessment Due'), ('certificate_issued', 'Certificate Issued'), ('certificate_expiring', 'Certificate Expiring'), ('announcement', 'Announcement'), ('reminder', 'Reminder'), ('enrollment_created', 'Enrollment Created'), ('enrollment_overdue', 'Enrollment Overdue'), ('enrollment_reminder', 'Enrollment Reminder'), ('policy_updated', 'Policy Updated'), ('manager_digest', 'Manager Digest'), ('feedback_received', 'Feedback Received')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('channels', models.JSONField(default=list)),
                ('recipient_emails', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_outbox', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_outbox',
                'indexes': [models.Index(fields=['status'], name='notificatio_status_4f522d_idx'), models.Index(fields=['scheduled_for'], name='notificatio_schedul_05e0d8_idx'), models.Index(fields=['created_at'], name='notificatio_created_1faaf9_idx')],
            },
        ),
    ]
