// Migration adapters (use legacy types, call canonical services)
export { courseService } from './courseService';
export { learningPathService } from './learningPathService';
export { enrollmentService } from './enrollmentService';
export { progressService } from './progressService';
export { userService } from './userService';
export { assessmentService } from './assessmentService';
export { competencyService } from './competencyService';
export { competencyBadgeService } from './competencyBadgeService';
export { competencyFrameworkService } from './competencyFrameworkService';
export { remediationService } from './remediationService';
export { organizationService } from './organizationService';
export { departmentService } from './departmentService';
export { teamService } from './teamService';
export { auditService } from './auditService';
export { reportService } from './reportService';
export { certificateService } from './certificateService';
export { pipelineService } from './pipelineService';
export { statsService } from './statsService';
export { announcementService } from './announcementService';
export { observabilityService } from './observabilityService';
export { workspaceService } from './workspaceService';
export { onboardingService } from './onboardingService';
export { masterService } from './masterService';
export { resolveWorkspaceAccess, getDefaultRouteForRole } from './workspaceAccessService';
export { gapMatrixService } from './gapMatrixService';
export { adaptiveRecommendationService } from './adaptiveRecommendationService';
export { adaptivePolicyService } from './adaptivePolicyService';
export { adaptiveReleaseService } from './adaptiveReleaseService';
export { remediationTriggerService } from './remediationTriggerService';
export { forecastingService } from './forecastingService';
export { governanceService } from './governanceService';
export { knowledgeGraphService } from './knowledgeGraphService';
export { gnnInsightService } from './gnnInsightService';
export { baselineDiagnosticService } from './baselineDiagnosticService';
export { interventionService } from './interventionService';
export * as guidedService from './guidedService';

// Canonical services (Django-backed data model adapters)
export * as canonical from './canonical';
