# Generated by Django 5.0.2 on 2026-02-24 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiasScan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('results', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_scans', to='organizations.organization')),
            ],
            options={
                'db_table': 'bias_scans',
            },
        ),
        migrations.CreateModel(
            name='ExplainabilityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('decision_type', models.CharField(max_length=255)),
                ('input_ref', models.CharField(blank=True, max_length=255)),
                ('output_ref', models.CharField(blank=True, max_length=255)),
                ('rationale', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explainability_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'explainability_logs',
                'indexes': [models.Index(fields=['organization', 'model_name'], name='explainabil_organiz_d93b2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='GovernancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('policy_type', models.CharField(choices=[('ai_usage', 'AI Usage'), ('data_retention', 'Data Retention'), ('model_risk', 'Model Risk'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('content', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governance_policies', to='organizations.organization')),
            ],
            options={
                'db_table': 'governance_policies',
                'indexes': [models.Index(fields=['organization', 'policy_type'], name='governance__organiz_2cf2ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='HumanOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=255)),
                ('target_id', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_overrides', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'human_overrides',
                'indexes': [models.Index(fields=['organization', 'target_type'], name='human_overr_organiz_2a984d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('staged', 'Staged'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('rolled_back', 'Rolled Back')], default='staged', max_length=20)),
                ('metrics', models.JSONField(default=dict)),
                ('deployed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_versions', to='organizations.organization')),
            ],
            options={
                'db_table': 'model_versions',
                'unique_together': {('organization', 'model_name', 'version')},
            },
        ),
    ]
