# Generated by Django 5.0.2 on 2026-02-23 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencies', '0001_initial'),
        ('courses', '0002_course_ai_generated_course_competency_tag_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CognitiveProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bloom_mastery', models.JSONField(default=dict)),
                ('modality_strengths', models.JSONField(default=dict)),
                ('preferred_modality', models.CharField(blank=True, max_length=20)),
                ('avg_response_time_ms', models.IntegerField(blank=True, null=True)),
                ('accuracy_by_difficulty', models.JSONField(default=dict)),
                ('total_questions_answered', models.IntegerField(default=0)),
                ('total_assessments_taken', models.IntegerField(default=0)),
                ('last_assessment_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_profiles', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cognitive_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cognitive_profiles',
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='GapMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_bloom_level', models.IntegerField(default=0)),
                ('target_bloom_level', models.IntegerField(default=0)),
                ('gap_score', models.FloatField(default=0.0)),
                ('priority', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_entries', to='competencies.competency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_matrix_entries', to='organizations.organization')),
                ('recommended_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gap_recommendations', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_matrix_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'gap matrix entries',
                'db_table': 'gap_matrix',
                'unique_together': {('user', 'organization', 'competency')},
            },
        ),
    ]
