# Generated by Codex on 2026-02-24

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_question_knowledge_chunk_question_modality'),
        ('competencies', '0001_initial'),
        ('courses', '0002_course_ai_generated_course_competency_tag_and_more'),
        ('learning_intelligence', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemediationTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_gap_score', models.FloatField(default=0.3)),
                ('max_attempts', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_triggers', to='assessments.assessment')),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remediation_triggers', to='competencies.competency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_triggers', to='organizations.organization')),
                ('remediation_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_triggers', to='courses.course')),
            ],
            options={
                'db_table': 'remediation_triggers',
                'indexes': [
                    models.Index(fields=['organization', 'is_active'], name='remediatio_organiza_1637a1_idx'),
                    models.Index(fields=['competency'], name='remediatio_compete_571289_idx'),
                ],
            },
        ),
    ]
