# Generated by Django 5.0.2 on 2026-02-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_intelligence', '0002_remediation_trigger'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='remediationtrigger',
            new_name='remediation_organiz_4ba920_idx',
            old_name='remediatio_organiza_1637a1_idx',
        ),
        migrations.RenameIndex(
            model_name='remediationtrigger',
            new_name='remediation_compete_9b902e_idx',
            old_name='remediatio_compete_571289_idx',
        ),
    ]
