# Generated by Django 5.0.2 on 2026-02-24 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_adaptive_r_course__8ab751_idx_adaptive_re_course__b179a3_idx_and_more'),
        ('learning_intelligence', '0003_rename_remediatio_organiza_1637a1_idx_remediation_organiz_4ba920_idx_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptivePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('current_version', models.CharField(blank=True, max_length=50)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_policies', to='organizations.organization')),
            ],
            options={
                'db_table': 'adaptive_policies',
            },
        ),
        migrations.CreateModel(
            name='AdaptiveDecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('reward', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_decisions', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_decisions', to=settings.AUTH_USER_MODEL)),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='learning_intelligence.adaptivepolicy')),
            ],
            options={
                'db_table': 'adaptive_decision_logs',
            },
        ),
        migrations.CreateModel(
            name='AdaptiveRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('recommend_course', 'Recommend Course'), ('nudge_course', 'Nudge Course Progress'), ('assign_remediation', 'Assign Remediation'), ('unlock_module', 'Unlock Module'), ('explore_paths', 'Explore Learning Paths')], max_length=40)),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_recommendations', to='organizations.organization')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='learning_intelligence.adaptivepolicy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'adaptive_recommendations',
            },
        ),
        migrations.CreateModel(
            name='FailureRiskSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_score', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('reasons', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_risk_snapshots', to='courses.course')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_risk_snapshots', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure_risk_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'failure_risk_snapshots',
            },
        ),
        migrations.AddIndex(
            model_name='adaptivepolicy',
            index=models.Index(fields=['organization', 'status'], name='adaptive_po_organiz_af120a_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptivedecisionlog',
            index=models.Index(fields=['organization', 'action_type'], name='adaptive_de_organiz_2ed4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptivedecisionlog',
            index=models.Index(fields=['created_at'], name='adaptive_de_created_f63dae_idx'),
        ),
        migrations.AddIndex(
            model_name='adaptiverecommendation',
            index=models.Index(fields=['organization', 'action_type'], name='adaptive_re_organiz_2680a1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adaptiverecommendation',
            unique_together={('organization', 'user', 'action_type')},
        ),
        migrations.AddIndex(
            model_name='failurerisksnapshot',
            index=models.Index(fields=['organization', 'risk_level'], name='failure_ris_organiz_d43945_idx'),
        ),
        migrations.AddIndex(
            model_name='failurerisksnapshot',
            index=models.Index(fields=['created_at'], name='failure_ris_created_59af3c_idx'),
        ),
    ]
