# Generated by Django 5.0.2 on 2026-02-24 23:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_question_knowledge_chunk_question_modality'),
        ('learning_intelligence', '0004_adaptivepolicy_adaptivedecisionlog_and_more'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineDiagnostic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target_type', models.CharField(choices=[('organization', 'Organization'), ('department', 'Department'), ('team', 'Team'), ('role', 'Role'), ('user', 'User')], default='organization', max_length=20)),
                ('target_id', models.CharField(blank=True, max_length=255)),
                ('role_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20)),
                ('results', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_diagnostics', to='assessments.assessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baseline_diagnostics', to='organizations.organization')),
            ],
            options={
                'db_table': 'baseline_diagnostics',
                'indexes': [models.Index(fields=['organization', 'status'], name='baseline_di_organiz_99aca7_idx'), models.Index(fields=['target_type'], name='baseline_di_target__bfaaca_idx')],
            },
        ),
        migrations.CreateModel(
            name='GapClosureSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('average_gap_score', models.FloatField(default=0.0)),
                ('total_open', models.IntegerField(default=0)),
                ('total_closed', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_closure_snapshots', to='organizations.organization')),
            ],
            options={
                'db_table': 'gap_closure_snapshots',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='gap_closure_organiz_15c063_idx')],
            },
        ),
        migrations.CreateModel(
            name='GNNInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('insight_type', models.CharField(blank=True, max_length=255)),
                ('metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gnn_insights', to='organizations.organization')),
            ],
            options={
                'db_table': 'gnn_insights',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='gnn_insight_organiz_8b07e9_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterventionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('executed', 'Executed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('outcome', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'intervention_logs',
                'indexes': [models.Index(fields=['organization', 'created_at'], name='interventio_organiz_e2b79f_idx')],
            },
        ),
    ]
