# Generated by Django 5.0.2 on 2026-02-25 09:16

from django.db import migrations, models


_BLOOM_WEIGHTS = {
    1: 1.0,
    2: 1.2,
    3: 1.5,
    4: 2.0,
    5: 2.5,
    6: 3.0,
}


def _safe_ratio(value, denominator):
    if denominator <= 0:
        return 0.0
    ratio = value / denominator
    if ratio < 0:
        return 0.0
    if ratio > 1:
        return 1.0
    return ratio


def _derive_current_level(profile):
    mastery = getattr(profile, 'bloom_mastery', None) or {}
    current = 0
    for level in range(1, 7):
        key_score = float(mastery.get(str(level), 0) or 0)
        if key_score >= 0.6:
            current = level
    return current


def _backfill_gap_components(apps, schema_editor):
    GapMatrix = apps.get_model('learning_intelligence', 'GapMatrix')
    CognitiveProfile = apps.get_model('learning_intelligence', 'CognitiveProfile')
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')

    for gap in GapMatrix.objects.select_related('competency').all().iterator():
        competency = gap.competency
        profile = CognitiveProfile.objects.filter(
            user_id=gap.user_id,
            organization_id=gap.organization_id,
        ).first()
        member = OrganizationMember.objects.filter(
            user_id=gap.user_id,
            organization_id=gap.organization_id,
        ).first()

        mastery = (profile.bloom_mastery if profile else {}) or {}
        modality_strengths = (profile.modality_strengths if profile else {}) or {}
        current_level = _derive_current_level(profile) if profile else 0

        target_level = int(gap.target_bloom_level or 0)
        if target_level <= 0 and competency and competency.bloom_level_target:
            target_level = int(competency.bloom_level_target)
        if target_level <= 0:
            target_level = 1

        bloom_score = float(mastery.get(str(target_level), 0) or 0)
        required_modalities = (competency.required_modalities if competency else []) or []
        primary_modality = required_modalities[0] if required_modalities else 'reading'
        modality_score = float(modality_strengths.get(primary_modality, 0) or 0)

        threshold_target = float(competency.threshold_score if competency else 0.75)
        learner_score = round((0.6 * bloom_score) + (0.4 * modality_score), 4)

        bloom_gap = max(0.0, 1.0 - bloom_score)
        modality_gap = max(0.0, 1.0 - modality_score)
        threshold_gap = max(0.0, threshold_target - learner_score)
        role_requirement_gap = max(0.0, _safe_ratio(target_level - current_level, float(max(target_level, 1))))

        bloom_weight = float(_BLOOM_WEIGHTS.get(target_level, 1.0))
        modality_weight = 1.0
        if member and member.role in {'instructor', 'team_lead', 'ld_manager', 'org_admin', 'super_admin'}:
            if primary_modality in {'speaking', 'writing'}:
                modality_weight = 1.2

        weighted_bloom_gap = bloom_gap * bloom_weight
        weighted_modality_gap = modality_gap * modality_weight
        weighted_sum = (
            (weighted_bloom_gap * 0.45)
            + (weighted_modality_gap * 0.25)
            + (threshold_gap * 0.20)
            + (role_requirement_gap * 0.10)
        )
        gap_score = round(min(1.0, max(0.0, weighted_sum / 1.5)), 4)

        gap.bloom_gap_component = round(bloom_gap, 4)
        gap.modality_gap_component = round(modality_gap, 4)
        gap.threshold_gap_component = round(threshold_gap, 4)
        gap.role_requirement_component = round(role_requirement_gap, 4)
        gap.weighted_bloom_gap = round(weighted_bloom_gap, 4)
        gap.weighted_modality_gap = round(weighted_modality_gap, 4)
        gap.bloom_weight = round(bloom_weight, 4)
        gap.modality_weight = round(modality_weight, 4)
        gap.threshold_score_target = round(threshold_target, 4)
        gap.learner_score = round(learner_score, 4)
        gap.gap_score = gap_score
        gap.gap_details = {
            'formula': '0.45*bloom + 0.25*modality + 0.20*threshold + 0.10*role_requirement',
            'primary_modality': primary_modality,
            'target_level': target_level,
            'source': 'weighted-gap-backfill-v1',
        }
        gap.save(update_fields=[
            'bloom_gap_component',
            'modality_gap_component',
            'threshold_gap_component',
            'role_requirement_component',
            'weighted_bloom_gap',
            'weighted_modality_gap',
            'bloom_weight',
            'modality_weight',
            'threshold_score_target',
            'learner_score',
            'gap_score',
            'gap_details',
            'updated_at',
        ])


def _noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('learning_intelligence', '0005_baselinediagnostic_gapclosuresnapshot_gnninsight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gapmatrix',
            name='bloom_gap_component',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gapmatrix',
            name='bloom_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gapmatrix',
            name='gap_details',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='gapmatrix',
            name='learner_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gapmatrix',
            name='modality_gap_component',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gapmatrix',
            name='modality_weight',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='gapmatrix',
            name='role_requirement_component',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gapmatrix',
            name='threshold_gap_component',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gapmatrix',
            name='threshold_score_target',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='gapmatrix',
            name='weighted_bloom_gap',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='gapmatrix',
            name='weighted_modality_gap',
            field=models.FloatField(default=0.0),
        ),
        migrations.RunPython(_backfill_gap_components, _noop_reverse),
    ]
