# Generated by Django 5.0.2 on 2026-02-23 22:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0001_initial'),
        ('knowledge', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ELSProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('current_phase', models.CharField(choices=[('ingest', 'Content Ingestion'), ('analyze', 'Needs Analysis'), ('design', 'Course Design'), ('develop', 'AI Development'), ('implement', 'Implementation'), ('evaluate', 'Evaluation'), ('personalize', 'Personalization'), ('portal', 'Manager Portal'), ('govern', 'Governance')], default='ingest', max_length=20)),
                ('phases_data', models.JSONField(default=dict)),
                ('created_course_ids', models.JSONField(default=list)),
                ('created_assessment_ids', models.JSONField(default=list)),
                ('created_learning_path_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='els_projects_created', to=settings.AUTH_USER_MODEL)),
                ('knowledge_documents', models.ManyToManyField(blank=True, related_name='els_projects', to='knowledge.knowledgedocument')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='els_projects_modified', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='els_projects', to='organizations.organization')),
            ],
            options={
                'db_table': 'els_projects',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ELSProjectPhase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('ingest', 'Content Ingestion'), ('analyze', 'Needs Analysis'), ('design', 'Course Design'), ('develop', 'AI Development'), ('implement', 'Implementation'), ('evaluate', 'Evaluation'), ('personalize', 'Personalization'), ('portal', 'Manager Portal'), ('govern', 'Governance')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('output_data', models.JSONField(default=dict)),
                ('bloom_distribution', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_records', to='genie.elsproject')),
            ],
            options={
                'db_table': 'els_project_phases',
                'ordering': ['project', 'phase'],
                'unique_together': {('project', 'phase')},
            },
        ),
    ]
