# Generated by Django 5.0.2 on 2026-02-25 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genie', '0002_elsproject_elsprojectphase'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='elsproject',
            name='autonomous_mode',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='elsproject',
            name='current_correlation_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='elsproject',
            name='current_idempotency_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='elsproject',
            name='current_run_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elsproject',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='elsproject',
            name='last_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='elsproject',
            name='last_outcome_package',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='elsproject',
            name='run_attempt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='elsproject',
            name='run_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elsproject',
            name='run_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elsproject',
            name='run_state',
            field=models.CharField(choices=[('idle', 'Idle'), ('queued', 'Queued'), ('ingesting', 'Ingesting'), ('analyzing', 'Analyzing'), ('designing', 'Designing'), ('developing', 'Developing'), ('implementing', 'Implementing'), ('evaluating', 'Evaluating'), ('completed', 'Completed'), ('failed', 'Failed'), ('exception_required', 'Exception Required'), ('canceled', 'Canceled')], default='idle', max_length=30),
        ),
        migrations.AddField(
            model_name='elsprojectphase',
            name='confidence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elsprojectphase',
            name='gate_result',
            field=models.CharField(choices=[('pending', 'Pending'), ('pass', 'Pass'), ('exception_required', 'Exception Required'), ('fail', 'Fail')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='elsprojectphase',
            name='quality_checks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='elsprojectphase',
            name='risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elsprojectphase',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('exception_required', 'Exception Required'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ELSProjectException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('ingest', 'Content Ingestion'), ('analyze', 'Needs Analysis'), ('design', 'Course Design'), ('develop', 'AI Development'), ('implement', 'Implementation'), ('evaluate', 'Evaluation'), ('personalize', 'Personalization'), ('portal', 'Manager Portal'), ('govern', 'Governance')], max_length=20)),
                ('reason_code', models.CharField(max_length=100)),
                ('reason_message', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('rejected', 'Rejected'), ('overridden', 'Overridden')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='genie.elsproject')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='els_exceptions_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'els_project_exceptions',
                'indexes': [models.Index(fields=['project', 'status'], name='els_project_project_723d23_idx'), models.Index(fields=['created_at'], name='els_project_created_d0d462_idx')],
            },
        ),
        migrations.CreateModel(
            name='ELSProjectRunMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_id', models.UUIDField()),
                ('phase', models.CharField(choices=[('ingest', 'Content Ingestion'), ('analyze', 'Needs Analysis'), ('design', 'Course Design'), ('develop', 'AI Development'), ('implement', 'Implementation'), ('evaluate', 'Evaluation'), ('personalize', 'Personalization'), ('portal', 'Manager Portal'), ('govern', 'Governance')], max_length=20)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('exception_required', 'Exception Required')], default='success', max_length=20)),
                ('duration_ms', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('token_cost', models.FloatField(default=0.0)),
                ('compute_cost', models.FloatField(default=0.0)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_metrics', to='genie.elsproject')),
            ],
            options={
                'db_table': 'els_project_run_metrics',
                'indexes': [models.Index(fields=['project', 'run_id'], name='els_project_project_603cff_idx'), models.Index(fields=['created_at'], name='els_project_created_150f00_idx')],
            },
        ),
    ]
