# Generated by Django 5.0.2 on 2026-02-23 22:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0003_assessment_assessment_subtype_assessment_bloom_level_and_more'),
        ('courses', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencyFramework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_frameworks', to='organizations.organization')),
            ],
            options={
                'db_table': 'competency_frameworks',
            },
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(blank=True, choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('bloom_level_target', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='competencies.competency')),
                ('framework', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencies', to='competencies.competencyframework')),
            ],
            options={
                'verbose_name_plural': 'competencies',
                'db_table': 'competencies',
            },
        ),
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('regulation', models.CharField(choices=[('gdpr', 'GDPR'), ('iso27001', 'ISO 27001'), ('hipaa', 'HIPAA'), ('sox', 'SOX'), ('pci_dss', 'PCI-DSS'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('due_days', models.IntegerField(default=30)),
                ('recurrence_days', models.IntegerField(blank=True, null=True)),
                ('penalty_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_policies', to='assessments.assessment')),
                ('linked_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_policies', to='courses.course')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_policies', to='organizations.organization')),
            ],
            options={
                'verbose_name_plural': 'compliance policies',
                'db_table': 'compliance_policies',
            },
        ),
        migrations.CreateModel(
            name='RoleCompetencyMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('required_level', models.CharField(choices=[('novice', 'Novice'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_mappings', to='competencies.competency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_competency_mappings', to='organizations.organization')),
            ],
            options={
                'db_table': 'role_competency_mappings',
                'unique_together': {('organization', 'role_name', 'competency')},
            },
        ),
    ]
