# Generated by Django 5.0.2 on 2026-02-24 13:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloomLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('verbs', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'bloom_levels',
                'ordering': ['level'],
            },
        ),
        migrations.AddField(
            model_name='competency',
            name='required_modalities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='competency',
            name='threshold_score',
            field=models.FloatField(default=0.75),
        ),
        migrations.CreateModel(
            name='CompetencyScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competency_tag', models.CharField(blank=True, max_length=255)),
                ('score', models.FloatField(default=0.0)),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('course_id', models.CharField(blank=True, max_length=100)),
                ('enrollment_id', models.CharField(blank=True, max_length=100)),
                ('assessment_id', models.CharField(blank=True, max_length=100)),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='competencies.competency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'competency_scores',
                'indexes': [models.Index(fields=['organization', 'competency_tag'], name='competency__organiz_5b56c3_idx'), models.Index(fields=['user'], name='competency__user_id_dc2b8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompetencySnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('competency_tag', models.CharField(max_length=255)),
                ('average_score', models.FloatField(default=0.0)),
                ('count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_snapshots', to='organizations.organization')),
            ],
            options={
                'db_table': 'competency_snapshots',
                'indexes': [models.Index(fields=['organization', 'competency_tag'], name='competency__organiz_b08ea7_idx'), models.Index(fields=['created_at'], name='competency__created_732bab_idx')],
            },
        ),
    ]
