# Generated by Django 5.0.2 on 2026-02-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0002_bloomlevel_competency_required_modalities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancepolicy',
            name='linked_competencies',
            field=models.ManyToManyField(blank=True, related_name='compliance_policies', to='competencies.competency'),
        ),
        migrations.AddField(
            model_name='rolecompetencymapping',
            name='priority',
            field=models.CharField(choices=[('mandatory', 'Mandatory'), ('recommended', 'Recommended'), ('optional', 'Optional')], default='mandatory', max_length=20),
        ),
    ]
