# Generated by Django 5.0.2 on 2026-02-24 13:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_type', models.CharField(choices=[('chunk', 'Knowledge Chunk'), ('competency', 'Competency'), ('concept', 'Concept')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_nodes', to='organizations.organization')),
            ],
            options={
                'db_table': 'knowledge_nodes',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEdge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.FloatField(default=1.0)),
                ('relation', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_edges', to='organizations.organization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_edges', to='knowledge.knowledgenode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_edges', to='knowledge.knowledgenode')),
            ],
            options={
                'db_table': 'knowledge_edges',
            },
        ),
        migrations.AddIndex(
            model_name='knowledgenode',
            index=models.Index(fields=['organization', 'node_type'], name='knowledge_n_organiz_e17169_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgeedge',
            index=models.Index(fields=['organization'], name='knowledge_e_organiz_767e77_idx'),
        ),
    ]
