# Generated by Django 5.0.2 on 2026-02-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgenode_knowledgeedge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgenode',
            name='node_type',
            field=models.CharField(choices=[('chunk', 'Knowledge Chunk'), ('competency', 'Competency'), ('concept', 'Concept'), ('learner', 'Learner'), ('assessment', 'Assessment'), ('bloom', 'Bloom Level')], max_length=20),
        ),
    ]
