# Generated by Django 5.0.2 on 2026-02-23 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_subtype',
            field=models.CharField(blank=True, choices=[('diagnostic', 'Diagnostic'), ('formative', 'Formative'), ('summative', 'Summative'), ('remediation', 'Remediation')], max_length=20),
        ),
        migrations.AddField(
            model_name='assessment',
            name='bloom_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='bloom_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
