# Generated by Django 5.0.2 on 2026-02-23 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessment_assessment_subtype_assessment_bloom_level_and_more'),
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='knowledge_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='knowledge.knowledgechunk'),
        ),
        migrations.AddField(
            model_name='question',
            name='modality',
            field=models.CharField(blank=True, choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('math', 'Math'), ('general_knowledge', 'General Knowledge')], max_length=20),
        ),
    ]
