# Generated by Django 5.0.2 on 2026-02-23 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='competency_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='competencies.competency'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_bloom_depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='bloom_band',
            field=models.CharField(blank=True, choices=[('foundation', 'Foundation'), ('application', 'Application'), ('analysis', 'Analysis'), ('critical', 'Critical/Creative')], max_length=20),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='bloom_level_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='bloom_level_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemodule',
            name='unlock_requires',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocks', to='courses.coursemodule'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='bloom_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='modality',
            field=models.CharField(blank=True, choices=[('reading', 'Reading'), ('writing', 'Writing'), ('listening', 'Listening'), ('speaking', 'Speaking'), ('math', 'Math'), ('general_knowledge', 'General Knowledge')], max_length=20),
        ),
    ]
