# Generated by Codex on 2026-02-24

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_question_knowledge_chunk_question_modality'),
        ('courses', '0002_course_ai_generated_course_competency_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdaptiveReleaseRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('prerequisite_module', 'Prerequisite Module'), ('assessment_passed', 'Assessment Passed'), ('bloom_mastery', 'Bloom Mastery')], max_length=30)),
                ('min_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('min_bloom_level', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptive_release_rules', to='assessments.assessment')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_release_rules', to='courses.course')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_release_rules', to='courses.coursemodule')),
                ('prerequisite_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adaptive_release_dependents', to='courses.coursemodule')),
            ],
            options={
                'db_table': 'adaptive_release_rules',
                'indexes': [
                    models.Index(fields=['course', 'module'], name='adaptive_r_course__8ab751_idx'),
                    models.Index(fields=['rule_type'], name='adaptive_r_rule_ty_ea5100_idx'),
                ],
            },
        ),
    ]
