# Generated by Django 5.0.2 on 2026-02-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_adaptive_release_rule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='adaptivereleaserule',
            new_name='adaptive_re_course__b179a3_idx',
            old_name='adaptive_r_course__8ab751_idx',
        ),
        migrations.RenameIndex(
            model_name='adaptivereleaserule',
            new_name='adaptive_re_rule_ty_160750_idx',
            old_name='adaptive_r_rule_ty_ea5100_idx',
        ),
    ]
