# Generated by Django 5.0.2 on 2026-02-25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_requests', to='organizations.organization')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_organization_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_requests',
            },
        ),
        migrations.CreateModel(
            name='OrganizationJoinRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='organizations.organization')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_join_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_join_requests',
            },
        ),
        migrations.CreateModel(
            name='OrganizationInviteCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('role', models.CharField(choices=[('learner', 'Learner'), ('instructor', 'Instructor'), ('team_lead', 'Team Lead'), ('ld_manager', 'L&D Manager'), ('org_admin', 'Org Admin'), ('super_admin', 'Super Admin')], default='learner', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_codes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invite_codes', to='organizations.organization')),
            ],
            options={
                'db_table': 'organization_invite_codes',
            },
        ),
        migrations.AddIndex(
            model_name='organizationrequest',
            index=models.Index(fields=['status', 'created_at'], name='organizatio_status_03111c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationrequest',
            index=models.Index(fields=['requested_by', 'status'], name='organizatio_reques_67d11f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationjoinrequest',
            index=models.Index(fields=['organization', 'status'], name='organizatio_organiz_7c905c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationjoinrequest',
            index=models.Index(fields=['requester', 'status'], name='organizatio_request_71ae9e_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvitecode',
            index=models.Index(fields=['organization', 'is_active'], name='organizatio_organiz_30180c_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationinvitecode',
            index=models.Index(fields=['code'], name='organizatio_code_c70898_idx'),
        ),
    ]
