# Generated by Django 5.0.2 on 2026-02-25 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_org_requests_invites_join_requests'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='organizationinvitecode',
            new_name='organizatio_organiz_041ef2_idx',
            old_name='organizatio_organiz_30180c_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationinvitecode',
            new_name='organizatio_code_0868c2_idx',
            old_name='organizatio_code_c70898_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationjoinrequest',
            new_name='organizatio_organiz_65b27e_idx',
            old_name='organizatio_organiz_7c905c_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationjoinrequest',
            new_name='organizatio_request_8a9410_idx',
            old_name='organizatio_request_71ae9e_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationrequest',
            new_name='organizatio_status_40e2b1_idx',
            old_name='organizatio_status_03111c_idx',
        ),
        migrations.RenameIndex(
            model_name='organizationrequest',
            new_name='organizatio_request_7d4356_idx',
            old_name='organizatio_reques_67d11f_idx',
        ),
    ]
